version: "3.8"
services:
  dynamo-admin:
    image: instructure/dynamo-local-admin
    container_name: "dynamoadmin_${PROJECT_NAME}"
    networks:
      - inner
    ports:
      - "8000:8000"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    links:
      - localstack
  localstack:
    image: localstack/localstack:0.12.5
    container_name: "localstack_${PROJECT_NAME}"
    networks:
      - inner
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_MAIN_ENDPOINT=http://localstack_${PROJECT_NAME}:4566
      - MAIN_CONTAINER_NAME=localstack_${PROJECT_NAME}
      - LOCALSTACK_SERVICES=${LOCALSTACK_SERVICES-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker}
      - DEBUG=${DEBUG-1}
      - DATA_DIR=${DATA_DIR-}
      - PORT_WEB_UI=${PORT_WEB_UI-8080}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${PWD}
      - LAMBDA_DOCKER_NETWORK=${PROJECT_NAME}
      - AWS_REGION=${AWS_REGION}
      - LAMBDA_REMOTE_DOCKER=${LAMBDA_REMOTE_DOCKER-0}
    volumes:
      - ${PWD}/.localstack/tmp/localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  inner:
    name: ${PROJECT_NAME}
    driver: bridge
